import {
  faArrowLeft,
  faArrowRight,
  faArrowDown,
  faArrowUp,
  faArrowRotateLeft,
  faArrowRotateRight,
  faArrowsRotate,
  faBroom,
  faChartColumn,
  faCheck,
  faCircleHalfStroke,
  faClockRotateLeft,
  faCopy,
  faDownload,
  faEye,
  faFileArrowDown,
  faFileExport,
  faFileImport,
  faHashtag,
  faImages,
  faEllipsis,
  faList,
  faMagnifyingGlass,
  faMagnifyingGlassMinus,
  faMagnifyingGlassPlus,
  faMinus,
  faPen,
  faPlus,
  faRightLeft,
  faRotateLeft,
  faScrewdriverWrench,
  faStar,
  faTag,
  faTags,
  faTextHeight,
  faTrash,
  faUpload,
  faXmark,
  faGear
} from "@fortawesome/free-solid-svg-icons";
import type { IconDefinition } from "@fortawesome/fontawesome-svg-core";

export const appIcons = {
  add: faPlus,
  apply: faCheck,
  arrowDown: faArrowDown,
  arrowLeft: faArrowLeft,
  arrowRight: faArrowRight,
  arrowUp: faArrowUp,
  clean: faBroom,
  clear: faXmark,
  close: faXmark,
  common: faTags,
  copy: faCopy,
  download: faDownload,
  export: faFileExport,
  exportFile: faFileArrowDown,
  settings: faGear,
  filter: faMagnifyingGlass,
  filterAdd: faMagnifyingGlassPlus,
  filterInvert: faCircleHalfStroke,
  highlight: faStar,
  history: faClockRotateLeft,
  images: faImages,
  import: faFileImport,
  known: faTag,
  order: faList,
  preview: faEye,
  remove: faMinus,
  removeItem: faTrash,
  rename: faPen,
  replace: faRightLeft,
  reset: faArrowsRotate,
  revert: faRotateLeft,
  showMore: faPlus,
  stats: faChartColumn,
  text: faTextHeight,
  tools: faScrewdriverWrench,
  undo: faArrowRotateLeft,
  upload: faUpload,
  zoomIn: faMagnifyingGlassPlus,
  zoomOut: faMagnifyingGlassMinus,
  redo: faArrowRotateRight,
  hashtag: faHashtag,
  more: faEllipsis
} satisfies Record<string, IconDefinition>;

export type AppIconName = keyof typeof appIcons;
